### ISSUE TITLE
Compiling of opencv 

### ISSUE THREAD

**Issue by lchunleo** [Borda/docker_python-opencv-ffmpeg#11]
Hi
Am new to the compiling of the opencv . Currently I had compiled the container with the docker file. However when I also install other stuff , the opencv nvdec stop working. I suspect that my subsequent stuff overwrite the new opencv. 

Can I check after compiling opencv , I should be not using pip install opencv-python . Is this correct? Thanks

**Comment by Borda** [comment]
> I should be not using pip install opencv-python . Is this correct?

correct with consecutive pip installation of any openCV you lose python connection to the compiled... you can check the ending of Dockerfile wich askes for openCV version
https://github.com/Borda/docker_python-opencv-ffmpeg/blob/0e1bb0ceb9c342595d094ec5c9d80efd0b951cc0/gpu/Dockerfile#L206
