### ISSUE TITLE
FFMPEG is missing

### ISSUE THREAD

**Issue by yuyou** [Borda/docker_python-opencv-ffmpeg#4]
I did not see ffmpeg is installed in the Dockerfile (for CUDA).

**Comment by leviethung2103** [comment]
@yuyou I think the author already included the FFMPEG in the Dockerfile at this line. 
https://github.com/Borda/docker_python-opencv-ffmpeg/blob/master/gpu/Dockerfile#L103

With this option, opencv automatically grabs the FFMPEG and build the FFMPEG. 

I'm not sure that the FFMPEG in this build is currently supporting the H264 or H265 or not. Let me check it out

**Comment by Borda** [comment]
@yuyou you are right, it was fixed recently, now it shall be complete and even populating multiple OpenCV versions 🐰
