### ISSUE TITLE
without opencv

### ISSUE THREAD

**Issue by AronWaterAron** [Borda/docker_python-opencv-ffmpeg#7]
I only need python and ffmpeg. 

may  I know if possible to provide an option without opencv

**Comment by Borda** [comment]
Hi, what specifically about the python version and/or ffmpeg do you need?
the main purpose here is to have Opnecv with python, the ffmpeg is just cherry on top...

it sounds that you just need this and skip all rest
https://github.com/Borda/docker_python-opencv-ffmpeg/blob/fc30c437fd8121222847e18812532cb83df7f3f7/cpu/Dockerfile#L19-L30
https://github.com/Borda/docker_python-opencv-ffmpeg/blob/fc30c437fd8121222847e18812532cb83df7f3f7/cpu/Dockerfile#L34

**Comment by Borda** [comment]
feel free to continue discussion here, just closing it as active issue as it out of the scope of this repo :rabbit:
